const fs = require('fs');

const raw = fs.readFileSync('backlinks.csv', 'utf16le');
const lines = raw.split('\n');

const headerLine = lines[0];
const separator = headerLine.includes('\t') ? '\t' : ',';

const headers = headerLine.split(separator).map(h => h.replace(/^"|"$/g, '').trim());

const idxUrl = headers.indexOf('Referring page URL');
const idxIsSpam = headers.indexOf('Is spam');
const idxDR = headers.indexOf('Domain rating');
const idxAnchor = headers.indexOf('Anchor');
const idxTitle = headers.indexOf('Referring page title');

console.log('Headers found:', {idxUrl, idxIsSpam, idxDR, idxAnchor, idxTitle});

if (idxUrl === -1) {
  console.error("Could not find 'Referring page URL' column.");
  process.exit(1);
}

const spamDomains = new Set();
let totalAnalyzed = 0;
let totalSpam = 0;

for (let i = 1; i < lines.length; i++) {
  const line = lines[i].trim();
  if (!line) continue;
  
  let cols = [];
  if (separator === '\t') {
    cols = line.split('\t').map(c => c.replace(/^"|"$/g, ''));
  } else {
    const re = /,(?=(?:(?:[^"]*"){2})*[^"]*$)/;
    cols = line.split(re).map(c => c.replace(/^"|"$/g, ''));
  }

  const url = cols[idxUrl];
  if (!url) continue;

  totalAnalyzed++;
  
  const isSpamFlag = idxIsSpam !== -1 ? cols[idxIsSpam] : 'false';
  const dr = idxDR !== -1 ? parseInt(cols[idxDR], 10) : 100;
  const anchor = (idxAnchor !== -1 ? cols[idxAnchor] : '').toLowerCase();
  const title = (idxTitle !== -1 ? cols[idxTitle] : '').toLowerCase();
  
  let isSpam = false;
  
  if (isSpamFlag === 'true' || isSpamFlag === '1') {
    isSpam = true;
  }
  
  const spammyKeywords = /casino|viagra|porn|cheap|xxx|escort|dating|cbd|gummies|pharmacy|slot|buy now|weight loss/i;
  
  if (dr < 10) {
    if (spammyKeywords.test(anchor) || spammyKeywords.test(title) || spammyKeywords.test(url)) {
      isSpam = true;
    }
  }

  // Also catch obvious blogspot/wordpress spam with 0 DR
  if (dr === 0 && (url.includes('.blogspot.com') || url.includes('.wordpress.com') || url.endsWith('.xyz'))) {
    isSpam = true;
  }

  if (isSpam) {
    totalSpam++;
    try {
      const hostname = new URL(url).hostname;
      const rootDomain = hostname.startsWith('www.') ? hostname.slice(4) : hostname;
      spamDomains.add('domain:' + rootDomain);
    } catch (e) {}
  }
}

console.log(`Analyzed ${totalAnalyzed} backlinks. Found ${totalSpam} spammy links pointing to ${spamDomains.size} unique domains.`);

const disavowContent = '# Disavow File for goexecution.com\n# Generated by AGY Link Audit\n\n' + Array.from(spamDomains).join('\n') + '\n';

fs.writeFileSync('disavow.txt', disavowContent, 'utf8');
console.log('Saved Disavow list to disavow.txt');
