import re

with open('lib/services.ts', 'r', encoding='utf-8') as f:
    content = f.read()

new_cm = '''  "content-marketing": {
    slug: "content-marketing",
    categorySlug: "digital-marketing",
    title: "B2B Content Marketing",
    seoTitle: "B2B Content Marketing Agency | Expert Content Creation Services",
    eyebrow: "Revenue-Driven Thought Leadership",
    description: "Go Execution is a premier B2B content marketing agency offering strategic content creation services, content development, and SEO content marketing.",
    intro: "Quality content is the engine of enterprise growth. As a specialized B2B content marketing agency, we research, draft, and publish high-authority assets that nurture complex buying committees.",
    overview: "Unlike a generic content marketing company, we operate as a dedicated B2B marketing agency and content marketing consultancy. Our strategists engineer SEO content marketing campaigns aligned with real search intent and long B2B sales cycles. From foundational content development and pipeline-focused blog writing to comprehensive content creation services, our B2B digital marketing agency ensures your thought leadership drives measurable revenue.",
    image: "/assets/images/logo-light.png",
    capabilities: [
      "B2B Content Marketing Agency Strategy",
      "Enterprise Content Creation Services",
      "SEO Content Marketing & Content Development",
      "B2B Digital Marketing Agency Lead Magnets"
    ],
    process: [
      ["Topical Research", "Our content marketing consultancy identifies high-value questions your target enterprise customers are asking."],
      ["Expert Content Creation", "Writing in-depth, well-researched articles and whitepapers that demonstrate industry authority."],
      ["Pipeline Alignment", "Integrating strategic internal links and calls-to-action to support the B2B sales cycle."],
      ["Performance Review", "Tracking traffic engagement, lead conversions, and pipeline influence generated by our content development."]
    ],
    faq: [
      ["What makes a B2B content marketing agency different?", "A dedicated B2B marketing agency understands long sales cycles, buying committees, and complex technical concepts, unlike B2C content mills."],
      ["Do you provide SEO content marketing?", "Yes, as a full-suite B2B digital marketing agency, our content creation services are deeply integrated with SEO strategies to ensure maximum organic visibility and lead generation."]
    ],
    relatedServices: ["social-media-marketing", "paid-advertising"],
    relatedIndustries: ["technology", "professional-services"],
    relatedBlogSlugs: ["b2b-saas-seo-strategy", "enterprise-seo-vs-traditional-seo", "how-long-does-seo-take-for-new-website"]
  },'''

pattern = re.compile(r'  "content-marketing": \{[\s\S]*?relatedBlogSlugs: \[.*?\]\n  \},')
content = pattern.sub(new_cm, content)

with open('lib/services.ts', 'w', encoding='utf-8') as f:
    f.write(content)
print("Successfully replaced content-marketing content with Content Gap keywords.")
